### ISSUE TITLE
develop yaml file to allow per repository configuration

### ISSUE THREAD

**Issue by craig8** [eclipse-volttron/github-tooling#3]
Use something similar for configuration of per repository data.  As you can see the volttron-core has a customization of pypi-project-name so that when generating a file that requires that it is available.

```yaml
default_github_organization: eclipse-volttron 
repositories:
  - name:  volttron-core
    pypi-project-name: volttron
  - name: volttron-listener
  - name: volttron-lib-web
  - name: volttron-testing
  - name: volttron-platform-driver
  - name: volttron-lib-base-driver
  - name: volttron-lib-fake-driver
  - name: volttron-lib-bacnet-driver
  - name: volttron-lib-actuator
  - name: volttron-lib-historian-base
  - name: volttron-lib-sql-historian
  - name: volttron-lib-historian-sqlite
  - name: volttron-lib-historian-postgres
```

There should be a class available to parse and validate that minimal sets of information is available.  Including, but not limited to methods for retrieving url to repository.
